; PlatformIO Project Configuration File
; Docs: https://docs.platformio.org/page/projectconf.html

[platformio]
default_envs = beacon1

[common]
framework = arduino
platform = espressif32
board = esp32dev
lib_deps_base = jgromes/RadioLib@^7.8.1
build_flags_base =
    -I include
    -DCORE_DEBUG_LEVEL=1

[env:beacon1]
extends = common
lib_deps = ${common.lib_deps_base}
build_flags =
    ${common.build_flags_base}
    -DBEACON_ID=1
build_src_filter = +<beacon/>

[env:beacon2]
extends = common
lib_deps = ${common.lib_deps_base}
build_flags =
    ${common.build_flags_base}
    -DBEACON_ID=2
build_src_filter = +<beacon/>

[env:beacon3]
extends = common
lib_deps = ${common.lib_deps_base}
build_flags =
    ${common.build_flags_base}
    -DBEACON_ID=3
build_src_filter = +<beacon/>

[env:gateway]
extends = common
lib_deps =
    ${common.lib_deps_base}
    knolleary/PubSubClient@^2.8
build_flags =
    ${common.build_flags_base}
build_src_filter = +<gateway/>

[env:writer]
extends = common
lib_deps =
    ${common.lib_deps_base}
    madhephaestus/ESP32Servo@^3.0.0
build_flags =
    ${common.build_flags_base}
build_src_filter = +<writer/>

[env:receiver]
extends = common
lib_deps = ${common.lib_deps_base}
build_flags =
    ${common.build_flags_base}
build_src_filter = +<receiver/>